### PR TITLE
Hactoberfest java 2020

### PR DESCRIPTION
**Pull request by rockstarabhishek**
Resubmitted Solutions for Problem 16 and 17 in Java.

### CODE REVIEW

**Comment by TheSpeedX** [comment]
Problem 20 still gives wrong answer.
Problem 17 has Error.

Please test codes in repl.it before sending PR.
Don`t Send Multiple PR For same question.
If you commit, It will reflect in open PR.

Send new PR only if old one is merged.

**Comment by rockstarabhishek** [comment]
Can you please check Solutions for Problem 16 , 17 , 20 in Java?
I have made proper changes and now all 3 are giving proper solutions.

**Comment by TheSpeedX** [comment]
Everything Looks Fine.
But there is an issue with Problem 17:
The expected answer is 21124. 
Your answer is 21224.

Kindly Fix it.

**Comment by TheSpeedX** [comment]
Thanks

**Comment by rockstarabhishek** [comment]
Pull request #27 is valid , Right?
And merged also.
Right??

**Comment by rockstarabhishek** [comment]
Please mark this PR as hacktoberfest-accepted.

**Pull request merged**
