### PR TITLE
Problem_42.java by tejgrover

### PR DESCRIPTION
**Pull request by tejgrover**
for hacktoberfest

### CODE REVIEW

**Comment by tejgrover** [comment]
Coded triangle numbers

**Comment by TheSpeedX** [comment]
Please follow the exact question of euler.
It says "Using [words.txt](https://projecteuler.net/project/resources/p042_words.txt), a 16K text file containing nearly two-thousand common English words, how many are triangle words?"

You might do a file read operation and load into a array and check the number of triangle words in array.

Note: You don't need to add words.txt to the repository

**Comment by tejgrover** [comment]
sir/maam,
i have solved this in hackerrank contest and this gives 100 score as it clears all the cases.
and i'll try to work on it.
Thanks for the response!

**Comment by tejgrover** [comment]
successfully done the exact question!

**Pull request merged**
