### PR TITLE
problem34.py file added

### PR DESCRIPTION
**Pull request by Bijay555**
Hey I have solved problem 34 and created PR. the file is in python folder.

### CODE REVIEW

**Comment by Bijay555** [comment]
Some extra files were created while I was coding 19 and 34 problem in pycharm . so I delete the above file. Now there is no wrong with the file. Please review it @TheSpeedX

**Comment by TheSpeedX** [comment]
The answer for problem 34 must be `40730`

**Comment by Bijay555** [comment]
@TheSpeedX I have modified the file. Now the answer is 40730. Please review it.

**Comment by Bijay555** [comment]
@TheSpeedX

**Comment by TheSpeedX** [comment]
Looks Fine

**Pull request merged**
